# Generated by Django 5.1.15 on 2026-06-30 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='businesses/', verbose_name='Imagen')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción SEO')),
            ],
            options={
                'verbose_name': 'Línea de negocio',
                'verbose_name_plural': 'Líneas de negocio',
                'ordering': ('order', 'name'),
            },
        ),
    ]
