# Generated by Django 5.2.18 on 2026-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='catalog_intro',
            field=models.CharField(blank=True, default='', help_text='Si queda vacía, se muestra Consulta los productos y servicios disponibles.', max_length=255, verbose_name='Introducción del catálogo'),
        ),
        migrations.AddField(
            model_name='business',
            name='featured_title',
            field=models.CharField(blank=True, default='', help_text='Si queda vacío, se muestra Productos y servicios destacados.', max_length=120, verbose_name='Título de destacados en el Home'),
        ),
    ]
