# Generated by Django 5.1.15 on 2026-06-30 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('site_name', models.CharField(default='Pámi', max_length=120, verbose_name='Nombre del sitio')),
                ('slogan', models.CharField(default='Donde encuentras todo para ti', max_length=180, verbose_name='Eslogan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción SEO')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
