# Generated by Django 5.1.15 on 2026-07-01 03:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_siteconfiguration_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('label', models.CharField(max_length=80, verbose_name='Etiqueta')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Abrir en nueva pestaña')),
            ],
            options={
                'verbose_name': 'Elemento de navegación',
                'verbose_name_plural': 'Elementos de navegación',
                'ordering': ('order', 'label'),
            },
        ),
    ]
