# Generated by Django 5.1.15 on 2026-07-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_navigationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_description',
            field=models.TextField(blank=True, default='Confecciones, papelería, tecnología y más, con soluciones para personas, empresas e instituciones.', verbose_name='Descripción del Hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/', verbose_name='Imagen del Hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_primary_button_text',
            field=models.CharField(default='Explorar catálogo', max_length=80, verbose_name='Texto botón principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_primary_button_url',
            field=models.CharField(default='/catalogo/', max_length=255, verbose_name='URL botón principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_secondary_button_text',
            field=models.CharField(default='Contáctanos', max_length=80, verbose_name='Texto botón secundario'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_secondary_button_url',
            field=models.CharField(default='/contacto/', max_length=255, verbose_name='URL botón secundario'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='Todo lo que tu empresa necesita, en un solo lugar.', max_length=180, verbose_name='Título del Hero'),
        ),
    ]
