# Generated by Django 5.1.15 on 2026-08-15 15:13

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_siteconfiguration_featured_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(max_length=255, validators=[apps.common.validators.validate_safe_link], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_image_extension], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/hero/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_image_extension], verbose_name='Imagen del Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_primary_button_url',
            field=models.CharField(default='/catalogo/', max_length=255, validators=[apps.common.validators.validate_safe_link], verbose_name='URL botón principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_secondary_button_url',
            field=models.CharField(default='/contacto/', max_length=255, validators=[apps.common.validators.validate_safe_link], verbose_name='URL botón secundario'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_image_extension], verbose_name='Logo'),
        ),
    ]
