# Generated by Django 5.2.18 on 2026-10-07 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_initialize_editorial_texts'),
        ('site', '0010_separate_hero_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_products_limit',
            field=models.PositiveSmallIntegerField(default=2, help_text='De 1 a 12. Se muestran los productos marcados de la línea destacada, según Orden y Nombre.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Cantidad de productos destacados'),
        ),
        migrations.AddConstraint(
            model_name='siteconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('featured_products_limit__gte', 1), ('featured_products_limit__lte', 12)), name='site_featured_products_limit_valid_range'),
        ),
    ]
