# Generated by Django 5.1.15 on 2026-06-30 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, max_length=255, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/posts/', verbose_name='Imagen')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción SEO')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='businesses.business', verbose_name='Línea de negocio')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
