# Generated by Django 5.1.15 on 2026-08-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
            ],
            options={
                'verbose_name': 'Respaldo de base de datos',
                'verbose_name_plural': 'Respaldos de base de datos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.auditlog',),
        ),
    ]
