# Generated by Django 5.1.15 on 2026-08-22 02:45

import apps.common.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Información adicional'),
        ),
        migrations.AddField(
            model_name='product',
            name='commercial_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('quote', 'Bajo cotización'), ('coming_soon', 'Próximamente')], default='available', max_length=20, verbose_name='Estado comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.CharField(blank=True, max_length=255, validators=[apps.common.validators.validate_safe_link], verbose_name='Enlace de demostración'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.TextField(blank=True, verbose_name='Público objetivo'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Característica del producto',
                'verbose_name_plural': 'Características del producto',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(upload_to='catalog/products/gallery/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_image_extension], verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen del producto',
                'verbose_name_plural': 'Imágenes del producto',
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
