# Generated by Django 5.2.18 on 2026-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Aparece en el Home si pertenece a la línea destacada y está activo y publicado. Se muestran hasta dos marcados, según Orden y Nombre.', verbose_name='Mostrar en destacados'),
        ),
    ]
