# Generated by Django 5.2.18 on 2026-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_preserve_current_featured_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Aparece en el Home si pertenece a la línea destacada y está activo y publicado. La cantidad se configura en Configuración del sitio; se priorizan Orden y Nombre.', verbose_name='Mostrar en destacados'),
        ),
    ]
