# Generated by Django 5.2.18 on 2026-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_configurable_featured_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_detail_button',
            field=models.BooleanField(default=False, help_text='Controla el botón en destacados y catálogo. La página de detalle y la lupa siguen disponibles.', verbose_name='Mostrar botón Ver detalle'),
        ),
    ]
