# Generated by Django 5.1.15 on 2026-06-30 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(max_length=170, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/', verbose_name='Imagen')),
                ('client_name', models.CharField(blank=True, max_length=120, verbose_name='Cliente')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Fecha del proyecto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='Título SEO')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción SEO')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_projects', to='businesses.business', verbose_name='Línea de negocio')),
            ],
            options={
                'verbose_name': 'Proyecto de portafolio',
                'verbose_name_plural': 'Proyectos de portafolio',
                'ordering': ('business', 'order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('business', 'slug'), name='unique_portfolio_project_slug_per_business')],
            },
        ),
    ]
