# Generated by Django 5.1.15 on 2026-08-15 15:13

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/', validators=[apps.common.validators.validate_file_size, apps.common.validators.validate_image_extension], verbose_name='Imagen'),
        ),
    ]
